// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCZykedIjyJrjKkW5LYAmzXLeZ7dj2zQ',
    appId: '1:1070368192547:web:2063427e2fd4c576d0d996',
    messagingSenderId: '1070368192547',
    projectId: 'hediaty-e96fc',
    authDomain: 'hediaty-e96fc.firebaseapp.com',
    storageBucket: 'hediaty-e96fc.firebasestorage.app',
    measurementId: 'G-YK7X5PYHYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbKximbyc3N_MXQNqNHU4xJka8hFmIwHo',
    appId: '1:1070368192547:android:ce90a3c6efe2b43dd0d996',
    messagingSenderId: '1070368192547',
    projectId: 'hediaty-e96fc',
    storageBucket: 'hediaty-e96fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5GPU_6788Pa4DmFf6M_9PIfLwRTeghY',
    appId: '1:1070368192547:ios:4f7dd95d06c3605fd0d996',
    messagingSenderId: '1070368192547',
    projectId: 'hediaty-e96fc',
    storageBucket: 'hediaty-e96fc.firebasestorage.app',
    iosBundleId: 'com.example.hedieatyfinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz5GPU_6788Pa4DmFf6M_9PIfLwRTeghY',
    appId: '1:1070368192547:ios:4f7dd95d06c3605fd0d996',
    messagingSenderId: '1070368192547',
    projectId: 'hediaty-e96fc',
    storageBucket: 'hediaty-e96fc.firebasestorage.app',
    iosBundleId: 'com.example.hedieatyfinalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLCZykedIjyJrjKkW5LYAmzXLeZ7dj2zQ',
    appId: '1:1070368192547:web:0bd257fa74102829d0d996',
    messagingSenderId: '1070368192547',
    projectId: 'hediaty-e96fc',
    authDomain: 'hediaty-e96fc.firebaseapp.com',
    storageBucket: 'hediaty-e96fc.firebasestorage.app',
    measurementId: 'G-3QC9BTCXQ5',
  );
}
